[package]
name = "map_demo"
version = "0.1.0"
authors = ["daheige <zhuwei313@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
