[package]
name = "trait_demo2"
version = "0.1.0"
authors = ["daheige <zhuwei313@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path="./mylib"}
